// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nryjbcryvfyczzxesude.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yeWpiY3J5dmZ5Y3p6eGVzdWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MjQ0MzUsImV4cCI6MjA3NDUwMDQzNX0.PD8X_GGwmVt5HHSMbzjo6VGU0JnWX8zny0f8Udfe6Bw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});